### ISSUE TITLE
No more basic auth

### ISSUE THREAD

**Issue by ChipWolf** [troykinsella/concourse-fly-resource#10]
In 5.2.0 basic auth results in 401 responses from the API, so, the resource fails to get the fly binary from the server
oauth flow will need to be implemented or an alternative source for the fly binary

**Comment by vinaykonanki** [comment]
I don't think we need any auth to download CLI after 5.2?

I can do 

```
curl -SsL 'https://concourse-test.company.com/api/v1/cli?arch=amd64&platform=linux' -o ./fly
```
without needing any auth. Maybe that's what we need. Just to remove the '-u' option.

**Comment by acarsercan** [comment]
Can this be merged?

**Comment by zwadderich** [comment]
Do you have an update on this?

**Comment by troykinsella** [comment]
Oauth isn't required for Concourse 5.x support. The `2.0.0` image tag (`latest` as of this comment) has been tested to work with Concourse 5.4.1.

**Comment by troykinsella** [comment]
As basic auth has been fixed on `master`, I'm going to close this and treat oauth support separately. Thanks!
