### ISSUE TITLE
Insecure SSL certificate support

### ISSUE THREAD

**Issue by ggeorgiev** [troykinsella/concourse-fly-resource#2]
I am having a pipeline that is using insecure SSL certificate, and I get:

Fetching fly...
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

I do not see how, I can explain to the fly resource that, and it to use -k when interacting with it.

**Comment by troykinsella** [comment]
For posterity, use the `insecure` source configuration option for this.
